<?php
/**
 * Dữ liệu bổ sung theo menu mới: FDI, Tax & accounting (tiếng Anh), Đào tạo kế toán,
 * và các dịch vụ khác tách riêng (hoá đơn điện tử, chữ ký số, tạm ngừng, giải thể…).
 * Giá để "Liên hệ" – điền giá thật ở Dịch vụ → sửa từng dịch vụ. Kiểm tra lại quy định mới nhất trước khi quảng bá.
 *
 * @package Flatsome_Dichvu
 */

defined( 'ABSPATH' ) || exit;

$sgd_p_dv = "Tiếp nhận yêu cầu | Tư vấn miễn phí, kiểm tra hồ sơ và báo giá trọn gói | Trong 15 phút\nSoạn hồ sơ | Chuyên viên soạn toàn bộ giấy tờ, gửi khách ký | 1 ngày\nNộp & theo dõi | Nộp hồ sơ tới cơ quan có thẩm quyền, xử lý yêu cầu bổ sung (nếu có) | Theo thời hạn của cơ quan\nBàn giao | Giao kết quả tận nơi, hướng dẫn các việc cần làm tiếp theo | Khi có kết quả";
$sgd_p_dt = "Đăng ký | Tư vấn khoá học phù hợp trình độ, chọn lịch học | Trong ngày\nHọc lý thuyết | Hệ thống hoá kiến thức theo quy định hiện hành | Theo lịch khai giảng\nThực hành | Làm trên chứng từ, sổ sách, tờ khai mô phỏng doanh nghiệp thật | Trong khoá\nHỗ trợ sau khoá | Giải đáp khi đi làm thực tế | Sau khi kết thúc";

return array(
	'groups'   => array(
		'dao-tao' => array( 'Đào tạo kế toán', 'users', 6, 'Khoá học kế toán thực hành: kế toán tổng hợp, kế toán thuế, làm sổ sách kế toán trên chứng từ thực tế – dành cho người mới đi làm, chủ doanh nghiệp nhỏ và kế toán muốn nâng cao.' ),
	),
	'services' => array(
		// ---------------- Thành lập ----------------
		array(
			'slug'      => 'fdi-company-establishment',
			'short'     => 'FDI company establishment',
			'group'     => 'thanh-lap-doanh-nghiep',
			'title'     => 'FDI company establishment in Vietnam',
			'excerpt'   => 'Company establishment service for foreign investors in Vietnam: investment registration certificate (IRC), enterprise registration certificate (ERC), seal, bank account and post-licensing compliance.',
			'subtitle'  => 'One-stop service for foreign investors – from investment license to tax registration',
			'price'     => 'Liên hệ',
			'duration'  => 'IRC + ERC (theo dự án)',
			'icon'      => 'globe',
			'includes'  => "Consulting on business lines open to foreign investors and market-access conditions\nPreparing and filing the Investment Registration Certificate (IRC) application\nPreparing and filing the Enterprise Registration Certificate (ERC) application\nCompany seal, capital account and initial tax registration\nPost-licensing compliance: capital contribution, reporting, accounting",
			'documents' => "Passport (individual investor) or certificate of incorporation (corporate investor), legalised and translated\nProof of financial capacity (bank statement or audited financial statements)\nOffice lease agreement in Vietnam\nProposed business lines, charter capital and project scale",
			'process'   => "Consulting | Review business lines and conditions for foreign investment | 1–2 days\nInvestment certificate | Prepare and file the IRC application | Per authority's processing time\nEnterprise certificate | File the ERC application after the IRC is issued | 3 working days\nPost-licensing | Seal, capital account, tax registration, capital contribution | After licensing",
			'faq'       => "What is the difference between IRC and ERC? | The IRC (Investment Registration Certificate) approves the investment project; the ERC (Enterprise Registration Certificate) establishes the company. Most foreign-invested companies need both.\nIs there a minimum capital requirement? | It depends on the business line. Capital must be sufficient for the project; some conditional business lines have specific requirements.\nDo I need to be in Vietnam? | Not necessarily. Documents can be signed abroad and legalised; we handle the filing.",
			'content'   => array(
				'Who is this service for?'     => 'Foreign individuals and companies who want to set up a 100% foreign-owned or joint-venture company in Vietnam. We advise on market-access conditions for your business lines before filing, so the application is accepted the first time.',
				'What you receive'             => 'Investment Registration Certificate, Enterprise Registration Certificate, company seal, tax registration and a checklist of compliance tasks after licensing (capital contribution deadline, reporting, accounting and tax filing).',
				'Ngôn ngữ / Language'          => 'Chuyên viên hỗ trợ bằng tiếng Việt và tiếng Anh. Our consultants work in Vietnamese and English.',
			),
		),
		// ---------------- Kế toán ----------------
		array(
			'slug'      => 'tax-and-accounting-service',
			'short'     => 'Tax and accounting service',
			'group'     => 'ke-toan',
			'title'     => 'Tax and accounting service in Vietnam',
			'excerpt'   => 'Monthly bookkeeping, tax filing, payroll and annual financial statements for foreign-invested companies and representative offices in Vietnam – reports in English.',
			'subtitle'  => 'Bookkeeping, tax returns and financial statements – reports in English',
			'price'     => 'Liên hệ',
			'duration'  => 'Theo tháng / quý / năm',
			'icon'      => 'calculator',
			'includes'  => "Monthly bookkeeping in line with Vietnamese Accounting Standards\nVAT, corporate income tax and personal income tax returns\nPayroll and social insurance declarations\nAnnual financial statements and tax finalisation\nManagement reports in English",
			'documents' => "Sales and purchase invoices, bank statements\nLabour contracts and payroll data\nPrevious tax returns and financial statements (if any)",
			'process'   => "Assessment | Review your transactions, invoices and reporting needs | 1 day\nEngagement | Fixed monthly fee, confidentiality agreement | Start of period\nMonthly work | Receive documents, record transactions, file tax returns | Every month\nReporting | Monthly/quarterly management reports in English | Monthly / quarterly",
			'faq'       => "Can you report in English? | Yes. Statutory reports follow Vietnamese standards; management reports are prepared in English.\nDo representative offices need accounting? | Representative offices do not do business, but still have obligations such as personal income tax for staff and periodic reports.",
			'content'   => array(
				'Accounting for foreign-invested companies' => 'Foreign-invested companies must keep books under Vietnamese Accounting Standards, file tax returns monthly or quarterly and prepare annual financial statements. We take care of the whole cycle so you can focus on your business.',
				'Dịch vụ kế toán cho doanh nghiệp FDI'       => 'Dịch vụ kế toán, thuế trọn gói cho doanh nghiệp có vốn đầu tư nước ngoài và văn phòng đại diện; báo cáo quản trị song ngữ Việt – Anh.',
			),
		),
		// ---------------- Đào tạo ----------------
		array(
			'slug'      => 'khoa-hoc-ke-toan-tong-hop',
			'short'     => 'Kế toán tổng hợp',
			'group'     => 'dao-tao',
			'title'     => 'Khoá học kế toán tổng hợp thực hành',
			'excerpt'   => 'Khoá học kế toán tổng hợp thực hành trên chứng từ thực tế: hạch toán, lập sổ sách, báo cáo tài chính – phù hợp người mới đi làm và kế toán muốn hệ thống lại kiến thức.',
			'subtitle'  => 'Thực hành trên chứng từ, sổ sách mô phỏng doanh nghiệp thật',
			'price'     => 'Liên hệ',
			'duration'  => 'Theo lịch khai giảng',
			'icon'      => 'users',
			'includes'  => "Nguyên lý kế toán và hệ thống tài khoản\nHạch toán nghiệp vụ mua bán, kho, tài sản cố định, tiền lương\nLập sổ sách và báo cáo tài chính cuối năm\nThực hành trên phần mềm kế toán\nTài liệu và bài tập thực hành",
			'documents' => '',
			'process'   => $sgd_p_dt,
			'faq'       => "Chưa học kế toán có theo được không? | Khoá học bắt đầu từ nguyên lý cơ bản, phù hợp cả người mới.\nCó được thực hành trên phần mềm không? | Có, học viên thực hành trên phần mềm kế toán và chứng từ mô phỏng.",
			'content'   => array(
				'Khoá học dành cho ai?' => 'Sinh viên mới ra trường, người chuyển ngành, chủ doanh nghiệp nhỏ muốn tự kiểm soát sổ sách, kế toán viên muốn hệ thống lại kiến thức tổng hợp. (Nội dung mẫu – cập nhật chương trình, lịch học, học phí thật.)',
				'Học xong làm được gì?' => 'Tự hạch toán các nghiệp vụ thường gặp, lập sổ sách và báo cáo tài chính năm, phối hợp làm việc với cơ quan thuế.',
			),
		),
		array(
			'slug'      => 'khoa-hoc-ke-toan-thue',
			'short'     => 'Kế toán thuế',
			'group'     => 'dao-tao',
			'title'     => 'Khoá học kế toán thuế',
			'excerpt'   => 'Khoá học kế toán thuế: kê khai thuế GTGT, TNCN, TNDN, quyết toán thuế, xử lý hoá đơn điện tử – học trên tờ khai thực tế.',
			'subtitle'  => 'Kê khai, quyết toán thuế và xử lý hoá đơn trên hồ sơ thực tế',
			'price'     => 'Liên hệ',
			'duration'  => 'Theo lịch khai giảng',
			'icon'      => 'tax',
			'includes'  => "Kê khai thuế GTGT theo tháng/quý\nThuế thu nhập cá nhân, quyết toán TNCN\nThuế thu nhập doanh nghiệp, quyết toán năm\nHoá đơn điện tử: lập, điều chỉnh, thay thế\nCác lỗi thường gặp khi cơ quan thuế kiểm tra",
			'documents' => '',
			'process'   => $sgd_p_dt,
			'faq'       => "Khoá học có cập nhật quy định mới không? | Chương trình cập nhật theo văn bản thuế hiện hành tại thời điểm khai giảng.",
			'content'   => array(
				'Nội dung khoá học' => 'Từ đăng ký, kê khai đến quyết toán các loại thuế chính của doanh nghiệp vừa và nhỏ; thực hành lập tờ khai trên phần mềm hỗ trợ kê khai. (Nội dung mẫu.)',
			),
		),
		array(
			'slug'      => 'khoa-hoc-so-sach-ke-toan',
			'short'     => 'Sổ sách kế toán',
			'group'     => 'dao-tao',
			'title'     => 'Khoá học làm sổ sách kế toán',
			'excerpt'   => 'Khoá học làm sổ sách kế toán từ chứng từ gốc: sổ nhật ký chung, sổ cái, sổ chi tiết, bảng cân đối – thực hành trên bộ chứng từ hoàn chỉnh.',
			'subtitle'  => 'Từ chứng từ gốc đến sổ cái và báo cáo – học bằng làm',
			'price'     => 'Liên hệ',
			'duration'  => 'Theo lịch khai giảng',
			'icon'      => 'doc',
			'includes'  => "Sắp xếp, kiểm tra chứng từ gốc\nGhi sổ nhật ký chung, sổ cái, sổ chi tiết\nĐối chiếu, khoá sổ cuối kỳ\nLập bảng cân đối số phát sinh",
			'documents' => '',
			'process'   => $sgd_p_dt,
			'faq'       => "Cần chuẩn bị gì? | Máy tính cá nhân; tài liệu và bộ chứng từ thực hành được cung cấp.",
			'content'   => array(
				'Học trên bộ chứng từ thật' => 'Học viên làm trọn một kỳ kế toán từ chứng từ đến sổ sách, nắm được cách sắp xếp hồ sơ để sẵn sàng khi quyết toán. (Nội dung mẫu.)',
			),
		),
		// ---------------- Thay đổi GPKD (tách riêng theo menu) ----------------
		array(
			'slug'      => 'doi-ten-cong-ty',
			'short'     => 'Thay đổi tên công ty',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Thủ tục thay đổi tên công ty',
			'excerpt'   => 'Dịch vụ thay đổi tên công ty trọn gói: kiểm tra trùng tên, soạn hồ sơ, nộp online, khắc lại con dấu và hướng dẫn cập nhật tên mới với thuế, ngân hàng, hoá đơn.',
			'subtitle'  => 'Kiểm tra trùng tên, nộp hồ sơ online – không cần đi lại',
			'price'     => 'Liên hệ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'edit',
			'includes'  => "Tư vấn, kiểm tra tên mới không trùng/gây nhầm lẫn\nSoạn quyết định, biên bản họp, thông báo thay đổi\nNộp hồ sơ online, theo dõi đến khi có kết quả\nKhắc lại con dấu theo tên mới\nHướng dẫn cập nhật tên mới với ngân hàng, hoá đơn, hợp đồng",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nTên mới dự kiến (2 – 3 phương án)\nCCCD người đại diện theo pháp luật",
			'process'   => $sgd_p_dv,
			'faq'       => "Đổi tên công ty có phải đổi mã số thuế không? | Không. Mã số doanh nghiệp giữ nguyên, chỉ thay đổi tên trên giấy chứng nhận đăng ký doanh nghiệp.\nSau khi đổi tên cần làm gì? | Khắc lại con dấu, cập nhật tên trên hoá đơn điện tử, tài khoản ngân hàng, biển hiệu và hợp đồng với đối tác.",
			'content'   => array(
				'Khi nào cần đổi tên công ty?' => 'Khi tái định vị thương hiệu, đổi chủ sở hữu, mở rộng lĩnh vực hoặc tên cũ gặp vấn đề về nhãn hiệu. Doanh nghiệp đăng ký thay đổi trong thời hạn 10 ngày kể từ ngày có thay đổi.',
			),
		),
		array(
			'slug'      => 'doi-dai-dien-phap-luat',
			'short'     => 'Đổi người đại diện pháp luật',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Thủ tục thay đổi người đại diện theo pháp luật',
			'excerpt'   => 'Dịch vụ thay đổi người đại diện theo pháp luật, giám đốc công ty: soạn hồ sơ, nộp online, cập nhật thông tin với cơ quan thuế và ngân hàng.',
			'subtitle'  => 'Hồ sơ chuẩn ngay lần đầu – cập nhật thông tin với thuế, ngân hàng',
			'price'     => 'Liên hệ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'users',
			'includes'  => "Tư vấn chức danh, số lượng người đại diện theo điều lệ\nSoạn quyết định, biên bản họp, thông báo thay đổi\nNộp hồ sơ online, nhận kết quả\nHướng dẫn đổi chữ ký số, chữ ký mẫu tại ngân hàng",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nCCCD người đại diện mới\nĐiều lệ công ty (nếu cần sửa đổi)",
			'process'   => $sgd_p_dv,
			'faq'       => "Công ty có thể có nhiều người đại diện theo pháp luật không? | Có, công ty TNHH và công ty cổ phần có thể có một hoặc nhiều người đại diện theo pháp luật; điều lệ quy định cụ thể số lượng, chức danh và quyền hạn.",
			'content'   => array(
				'Lưu ý khi thay đổi người đại diện' => 'Sau khi có kết quả, cần cập nhật chữ ký số, chữ ký mẫu ngân hàng và thông tin trên các hợp đồng đang thực hiện. Doanh nghiệp đăng ký thay đổi trong thời hạn 10 ngày kể từ ngày có thay đổi.',
			),
		),
		array(
			'slug'      => 'them-giam-thanh-vien-co-dong',
			'short'     => 'Thay đổi thành viên, cổ đông',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Thủ tục thêm, giảm thành viên – cổ đông',
			'excerpt'   => 'Dịch vụ thay đổi thành viên công ty TNHH, cổ đông công ty cổ phần: chuyển nhượng vốn, kết nạp thành viên mới, kê khai thuế thu nhập từ chuyển nhượng.',
			'subtitle'  => 'Chuyển nhượng vốn, kết nạp thành viên mới – kê khai thuế đầy đủ',
			'price'     => 'Liên hệ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'users',
			'includes'  => "Tư vấn hình thức: chuyển nhượng, tặng cho, góp thêm vốn\nSoạn hợp đồng chuyển nhượng, biên bản thanh lý\nSoạn và nộp hồ sơ thay đổi\nKê khai thuế thu nhập từ chuyển nhượng vốn (nếu có)",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nCCCD thành viên/cổ đông mới\nThông tin phần vốn chuyển nhượng",
			'process'   => $sgd_p_dv,
			'faq'       => "Chuyển nhượng vốn có phải nộp thuế không? | Thu nhập từ chuyển nhượng vốn có thể phải nộp thuế thu nhập cá nhân hoặc thu nhập doanh nghiệp; chuyên viên tính và kê khai giúp bạn.",
			'content'   => array(
				'Các trường hợp thay đổi thành viên, cổ đông' => 'Thành viên chuyển nhượng phần vốn góp, kết nạp thành viên mới góp vốn, thành viên rút vốn hoặc không góp đủ vốn đã cam kết. Mỗi trường hợp có hồ sơ và nghĩa vụ thuế khác nhau.',
			),
		),
		array(
			'slug'      => 'chuyen-doi-loai-hinh-cong-ty',
			'short'     => 'Chuyển đổi loại hình công ty',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Thủ tục chuyển đổi loại hình doanh nghiệp',
			'excerpt'   => 'Chuyển đổi công ty TNHH một thành viên sang hai thành viên, TNHH sang cổ phần và ngược lại, doanh nghiệp tư nhân sang công ty TNHH – trọn gói, giữ nguyên mã số thuế.',
			'subtitle'  => 'Giữ nguyên mã số doanh nghiệp – kế thừa quyền và nghĩa vụ',
			'price'     => 'Liên hệ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'building',
			'includes'  => "Tư vấn loại hình phù hợp mục tiêu góp vốn, quản trị\nSoạn điều lệ mới, quyết định, hồ sơ chuyển đổi\nNộp hồ sơ, nhận giấy chứng nhận mới\nKhắc dấu, cập nhật thông tin với thuế, ngân hàng",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nDanh sách thành viên/cổ đông sau chuyển đổi\nCCCD các thành viên/cổ đông",
			'process'   => $sgd_p_dv,
			'faq'       => "Chuyển đổi loại hình có phải làm lại mã số thuế không? | Không. Doanh nghiệp chuyển đổi giữ nguyên mã số doanh nghiệp và kế thừa toàn bộ quyền, nghĩa vụ của doanh nghiệp cũ.",
			'content'   => array(
				'Khi nào nên chuyển đổi loại hình?' => 'Khi có thêm thành viên góp vốn, cần huy động vốn bằng cổ phần hoặc muốn thu gọn cơ cấu sở hữu. Chuyên viên so sánh ưu nhược điểm từng loại hình theo kế hoạch của bạn.',
			),
		),
		array(
			'slug'      => 'cap-nhat-cccd-dang-ky-kinh-doanh',
			'short'     => 'Cập nhật CCCD',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Cập nhật CCCD trên đăng ký kinh doanh',
			'excerpt'   => 'Dịch vụ cập nhật số căn cước công dân (CCCD) của người đại diện, thành viên, cổ đông trên đăng ký doanh nghiệp khi đổi từ CMND sang CCCD hoặc cấp lại căn cước.',
			'subtitle'  => 'Đồng bộ thông tin căn cước – tránh vướng khi giao dịch thuế, ngân hàng',
			'price'     => 'Liên hệ',
			'duration'  => '2 – 3 ngày làm việc',
			'icon'      => 'doc',
			'includes'  => "Kiểm tra thông tin đang lưu trên hệ thống đăng ký doanh nghiệp\nSoạn và nộp hồ sơ bổ sung, cập nhật thông tin\nCập nhật thông tin người đại diện với cơ quan thuế (nếu cần)",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nCCCD mới của người cần cập nhật",
			'process'   => $sgd_p_dv,
			'faq'       => "Vì sao cần cập nhật CCCD trên đăng ký kinh doanh? | Thông tin giấy tờ pháp lý không khớp có thể gây vướng mắc khi ký số, giao dịch ngân hàng hoặc làm thủ tục thuế.",
			'content'   => array(
				'Ai cần cập nhật?' => 'Doanh nghiệp có người đại diện, thành viên, cổ đông đã đổi từ chứng minh nhân dân sang căn cước công dân hoặc được cấp lại căn cước. (Kiểm tra lại quy định mới nhất trước khi đăng.)',
			),
		),
		// ---------------- Dịch vụ khác ----------------
		array(
			'slug'      => 'hoa-don-dien-tu',
			'short'     => 'Hóa đơn điện tử',
			'group'     => 'dich-vu-khac',
			'title'     => 'Đăng ký hóa đơn điện tử cho doanh nghiệp, hộ kinh doanh',
			'excerpt'   => 'Đăng ký sử dụng hoá đơn điện tử, cài đặt phần mềm, phát hành mẫu hoá đơn và hướng dẫn lập, điều chỉnh, thay thế hoá đơn đúng quy định.',
			'subtitle'  => 'Đăng ký, phát hành và hướng dẫn sử dụng hoá đơn điện tử',
			'price'     => 'Liên hệ',
			'duration'  => '1 – 2 ngày làm việc',
			'icon'      => 'doc',
			'includes'  => "Tư vấn chọn nhà cung cấp và gói số hoá đơn phù hợp\nĐăng ký sử dụng hoá đơn điện tử với cơ quan thuế\nThiết kế mẫu hoá đơn, cài đặt phần mềm\nHướng dẫn lập, điều chỉnh, thay thế hoá đơn",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp / hộ kinh doanh\nChữ ký số còn hiệu lực\nLogo doanh nghiệp (nếu muốn in trên hoá đơn)",
			'process'   => $sgd_p_dv,
			'faq'       => "Doanh nghiệp mới thành lập có cần hoá đơn điện tử ngay không? | Doanh nghiệp cần đăng ký hoá đơn điện tử trước khi bán hàng, cung cấp dịch vụ và xuất hoá đơn cho khách.\nCần chữ ký số không? | Có, việc đăng ký và ký hoá đơn điện tử cần chữ ký số.",
			'content'   => array(
				'Khi nào cần hoá đơn điện tử?' => 'Doanh nghiệp, hộ kinh doanh khi bán hàng hoá, cung cấp dịch vụ phải lập hoá đơn điện tử theo quy định. Chúng tôi hỗ trợ trọn gói từ đăng ký đến khi xuất được hoá đơn đầu tiên.',
			),
		),
		array(
			'slug'      => 'chu-ky-so',
			'short'     => 'Chữ ký số',
			'group'     => 'dich-vu-khac',
			'title'     => 'Đăng ký chữ ký số (token) cho doanh nghiệp',
			'excerpt'   => 'Đăng ký mới, gia hạn chữ ký số (USB token) cho doanh nghiệp, hộ kinh doanh, cá nhân – dùng kê khai thuế, ký hoá đơn điện tử, bảo hiểm xã hội, hải quan.',
			'subtitle'  => 'Đăng ký mới và gia hạn – giao token, cài đặt tận nơi',
			'price'     => 'Liên hệ',
			'duration'  => '1 ngày làm việc',
			'icon'      => 'shield',
			'includes'  => "Tư vấn gói 1 – 3 năm phù hợp\nĐăng ký với nhà cung cấp, giao USB token\nCài đặt, đăng ký chữ ký số với cơ quan thuế, BHXH\nGia hạn khi sắp hết hạn",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nCCCD người đại diện theo pháp luật",
			'process'   => $sgd_p_dv,
			'faq'       => "Chữ ký số dùng để làm gì? | Ký điện tử tờ khai thuế, hoá đơn điện tử, hồ sơ bảo hiểm xã hội, hải quan và các giao dịch điện tử khác.\nHết hạn thì sao? | Cần gia hạn trước ngày hết hạn để không gián đoạn kê khai, xuất hoá đơn.",
			'content'   => array(
				'Chữ ký số cho doanh nghiệp' => 'Chữ ký số là công cụ bắt buộc để doanh nghiệp giao dịch điện tử với cơ quan thuế, bảo hiểm xã hội và ký hoá đơn điện tử. Chúng tôi giao token và cài đặt tận nơi.',
			),
		),
		array(
			'slug'      => 'tam-ngung-kinh-doanh',
			'short'     => 'Tạm ngừng kinh doanh',
			'group'     => 'dich-vu-khac',
			'title'     => 'Thủ tục tạm ngừng kinh doanh',
			'excerpt'   => 'Dịch vụ thông báo tạm ngừng kinh doanh cho công ty, chi nhánh, hộ kinh doanh: soạn hồ sơ, nộp online, xử lý nghĩa vụ thuế trong thời gian tạm ngừng.',
			'subtitle'  => 'Thông báo tạm ngừng đúng hạn – không bị phạt, không phát sinh thuế',
			'price'     => 'Liên hệ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'clock',
			'includes'  => "Tư vấn thời hạn và nghĩa vụ thuế khi tạm ngừng\nSoạn quyết định, thông báo tạm ngừng\nNộp hồ sơ online tới cơ quan đăng ký kinh doanh\nHướng dẫn kê khai thuế trước và sau thời gian tạm ngừng",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nThời gian dự kiến tạm ngừng\nCCCD người đại diện theo pháp luật",
			'process'   => $sgd_p_dv,
			'faq'       => "Phải thông báo trước bao lâu? | Doanh nghiệp phải thông báo bằng văn bản cho cơ quan đăng ký kinh doanh chậm nhất 03 ngày làm việc trước ngày tạm ngừng kinh doanh.\nMỗi lần được tạm ngừng tối đa bao lâu? | Thời hạn tạm ngừng mỗi lần thông báo không quá 01 năm; hết thời hạn có thể tiếp tục thông báo.",
			'content'   => array(
				'Khi nào nên tạm ngừng kinh doanh?' => 'Khi doanh nghiệp chưa hoạt động hoặc cần dừng hoạt động một thời gian nhưng chưa muốn giải thể. Tạm ngừng đúng thủ tục giúp không phải kê khai thuế trong thời gian tạm ngừng (trừ trường hợp tạm ngừng không trọn năm) và tránh bị phạt.',
			),
		),
		array(
			'slug'      => 'giai-the-doanh-nghiep',
			'short'     => 'Giải thể doanh nghiệp',
			'group'     => 'dich-vu-khac',
			'title'     => 'Thủ tục giải thể doanh nghiệp',
			'excerpt'   => 'Dịch vụ giải thể công ty trọn gói: quyết toán thuế, đóng mã số thuế, thanh lý tài sản, nộp hồ sơ giải thể – khách hàng không cần đi lại.',
			'subtitle'  => 'Trọn gói từ quyết toán thuế, đóng mã số thuế đến xoá tên doanh nghiệp',
			'price'     => 'Liên hệ',
			'duration'  => 'Theo hồ sơ thuế',
			'icon'      => 'stamp',
			'includes'  => "Rà soát nghĩa vụ thuế, hoá đơn, bảo hiểm\nQuyết toán thuế, chấm dứt hiệu lực mã số thuế\nSoạn quyết định, biên bản giải thể, thông báo giải thể\nNộp hồ sơ giải thể tới cơ quan đăng ký kinh doanh",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp, con dấu\nSổ sách, báo cáo thuế các năm\nDanh sách chủ nợ, hợp đồng còn hiệu lực (nếu có)",
			'process'   => $sgd_p_dv,
			'faq'       => "Giải thể mất bao lâu? | Phụ thuộc chủ yếu vào thời gian quyết toán thuế và đóng mã số thuế; doanh nghiệp có hồ sơ thuế đầy đủ sẽ nhanh hơn.\nCòn nợ thuế có giải thể được không? | Doanh nghiệp phải thanh toán hết các khoản nợ, nghĩa vụ thuế trước khi hoàn tất giải thể.",
			'content'   => array(
				'Điều kiện giải thể' => 'Doanh nghiệp chỉ được giải thể khi bảo đảm thanh toán hết các khoản nợ và nghĩa vụ tài sản khác. Chúng tôi rà soát hồ sơ thuế trước để dự kiến thời gian và chi phí sát thực tế.',
			),
		),
		array(
			'slug'      => 'dang-ky-kinh-doanh',
			'short'     => 'Đăng ký kinh doanh',
			'group'     => 'dich-vu-khac',
			'title'     => 'Dịch vụ đăng ký kinh doanh',
			'excerpt'   => 'Tư vấn chọn hình thức đăng ký kinh doanh phù hợp: hộ kinh doanh, công ty TNHH, công ty cổ phần, chi nhánh, địa điểm kinh doanh – làm hồ sơ trọn gói.',
			'subtitle'  => 'Chọn đúng hình thức ngay từ đầu – hồ sơ trọn gói, không đi lại',
			'price'     => 'Liên hệ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'building',
			'includes'  => "So sánh hộ kinh doanh và doanh nghiệp theo nhu cầu, thuế\nTư vấn ngành nghề, địa chỉ, vốn\nSoạn và nộp hồ sơ đăng ký\nNhận kết quả, hướng dẫn việc cần làm sau đăng ký",
			'documents' => "CCCD chủ hộ / thành viên góp vốn\nĐịa chỉ kinh doanh\nNgành nghề dự kiến",
			'process'   => $sgd_p_dv,
			'faq'       => "Nên đăng ký hộ kinh doanh hay công ty? | Hộ kinh doanh phù hợp quy mô nhỏ, ít giao dịch với doanh nghiệp; công ty phù hợp khi cần xuất hoá đơn thường xuyên, hợp tác, mở rộng. Chuyên viên tư vấn theo trường hợp cụ thể.",
			'content'   => array(
				'Các hình thức đăng ký kinh doanh' => 'Hộ kinh doanh, công ty TNHH, công ty cổ phần, chi nhánh và địa điểm kinh doanh có thủ tục, nghĩa vụ thuế và trách nhiệm khác nhau. Chúng tôi tư vấn để bạn chọn hình thức phù hợp rồi làm hồ sơ trọn gói.',
			),
		),
		array(
			'slug'      => 'thanh-lap-van-phong-dai-dien-nuoc-ngoai',
			'short'     => 'VPĐD nước ngoài',
			'group'     => 'dich-vu-khac',
			'title'     => 'Thành lập văn phòng đại diện của thương nhân nước ngoài',
			'excerpt'   => 'Dịch vụ xin giấy phép thành lập văn phòng đại diện của thương nhân nước ngoài tại Việt Nam: hợp pháp hoá giấy tờ, nộp hồ sơ, khắc dấu, đăng ký thuế.',
			'subtitle'  => 'Giấy phép văn phòng đại diện cho thương nhân nước ngoài – trọn gói',
			'price'     => 'Liên hệ',
			'duration'  => 'Theo thời hạn của Sở Công Thương',
			'icon'      => 'globe',
			'includes'  => "Kiểm tra điều kiện thành lập văn phòng đại diện\nHướng dẫn hợp pháp hoá lãnh sự, dịch thuật giấy tờ\nSoạn và nộp hồ sơ xin giấy phép\nKhắc dấu, đăng ký thuế, thông báo hoạt động",
			'documents' => "Giấy đăng ký kinh doanh của thương nhân nước ngoài (hợp pháp hoá lãnh sự)\nBáo cáo tài chính có kiểm toán năm gần nhất\nHộ chiếu/CCCD người đứng đầu văn phòng\nHợp đồng thuê địa điểm đặt văn phòng",
			'process'   => $sgd_p_dv,
			'faq'       => "Văn phòng đại diện có được kinh doanh không? | Không. Văn phòng đại diện chỉ thực hiện chức năng liên lạc, xúc tiến thương mại; không trực tiếp kinh doanh sinh lời.\nGiấy phép có thời hạn bao lâu? | Giấy phép thành lập văn phòng đại diện có thời hạn 05 năm và có thể gia hạn.",
			'content'   => array(
				'Văn phòng đại diện phù hợp với ai?' => 'Thương nhân nước ngoài muốn tìm hiểu thị trường, xúc tiến thương mại, liên lạc với đối tác tại Việt Nam trước khi đầu tư thành lập công ty.',
			),
		),
		array(
			'slug'      => 'dang-ky-ma-so-thue-ca-nhan',
			'short'     => 'Đăng ký MST cá nhân',
			'group'     => 'dich-vu-khac',
			'title'     => 'Đăng ký mã số thuế cá nhân',
			'excerpt'   => 'Hỗ trợ đăng ký, cập nhật mã số thuế cá nhân, đăng ký người phụ thuộc để giảm trừ gia cảnh – đúng quy định mới về sử dụng số định danh cá nhân.',
			'subtitle'  => 'Đăng ký, cập nhật thông tin thuế cá nhân và người phụ thuộc',
			'price'     => 'Liên hệ',
			'duration'  => '1 – 3 ngày làm việc',
			'icon'      => 'tax',
			'includes'  => "Kiểm tra tình trạng mã số thuế cá nhân hiện có\nĐăng ký mới hoặc cập nhật thông tin\nĐăng ký người phụ thuộc giảm trừ gia cảnh\nHướng dẫn tra cứu, quyết toán thuế TNCN",
			'documents' => "CCCD còn hiệu lực\nThông tin người phụ thuộc (nếu đăng ký giảm trừ gia cảnh)",
			'process'   => $sgd_p_dv,
			'faq'       => "Đã có CCCD gắn chip có cần đăng ký mã số thuế không? | Theo quy định mới, số định danh cá nhân được sử dụng thay cho mã số thuế cá nhân; tuy nhiên thông tin cần được cập nhật, đồng bộ với cơ quan thuế. Chuyên viên kiểm tra và hỗ trợ cụ thể.",
			'content'   => array(
				'Khi nào cần đăng ký / cập nhật mã số thuế cá nhân?' => 'Khi bắt đầu có thu nhập chịu thuế, đăng ký giảm trừ gia cảnh, quyết toán thuế TNCN hoặc thông tin cá nhân thay đổi. (Kiểm tra lại quy định mới nhất trước khi đăng.)',
			),
		),
		array(
			'slug'      => 'soan-thao-hop-dong',
			'short'     => 'Soạn thảo hợp đồng',
			'group'     => 'dich-vu-khac',
			'title'     => 'Dịch vụ soạn thảo hợp đồng',
			'excerpt'   => 'Soạn thảo, rà soát hợp đồng kinh tế, hợp đồng lao động, hợp đồng thuê nhà, hợp đồng góp vốn – bảo vệ quyền lợi, hạn chế rủi ro tranh chấp.',
			'subtitle'  => 'Hợp đồng chặt chẽ – bảo vệ quyền lợi doanh nghiệp',
			'price'     => 'Liên hệ',
			'duration'  => '1 – 3 ngày làm việc',
			'icon'      => 'edit',
			'includes'  => "Tìm hiểu giao dịch và mong muốn của khách hàng\nSoạn thảo hợp đồng theo mẫu riêng\nRà soát hợp đồng do đối tác gửi, chỉ ra rủi ro\nChỉnh sửa theo góp ý đến khi ký",
			'documents' => "Thông tin các bên\nNội dung giao dịch, giá trị, thời hạn\nHợp đồng nháp của đối tác (nếu có)",
			'process'   => $sgd_p_dv,
			'faq'       => "Có rà soát hợp đồng đối tác gửi không? | Có. Chúng tôi rà soát, ghi chú điều khoản rủi ro và đề xuất sửa đổi.",
			'content'   => array(
				'Các loại hợp đồng thường gặp' => 'Hợp đồng mua bán hàng hoá, cung cấp dịch vụ, hợp đồng lao động, thuê văn phòng, góp vốn, hợp tác kinh doanh. Mỗi hợp đồng được soạn theo giao dịch cụ thể, không dùng mẫu chung chung.',
			),
		),
	),
);
