<?php
/**
 * Dữ liệu mẫu: nhóm dịch vụ + dịch vụ (nội dung, bảng giá, quy trình, hồ sơ, FAQ).
 * Giá là GIÁ MẪU – sửa lại theo bảng giá thật của công ty trước khi chạy quảng cáo.
 *
 * @package Flatsome_Dichvu
 */

defined( 'ABSPATH' ) || exit;

$sgd_p_tl = "Tiếp nhận yêu cầu | Tư vấn miễn phí loại hình, tên, vốn, ngành nghề; báo giá trọn gói\nSoạn hồ sơ | Chuyên viên soạn toàn bộ hồ sơ, gửi khách ký (ký tại nhà hoặc ký số)\nNộp hồ sơ online | Nộp qua Cổng thông tin quốc gia về đăng ký doanh nghiệp, theo dõi đến khi được duyệt\nNhận kết quả | Giao giấy chứng nhận, con dấu và hồ sơ tận nơi\nHỗ trợ sau thành lập | Hướng dẫn các việc cần làm ngay: tài khoản ngân hàng, chữ ký số, hóa đơn điện tử, khai thuế";
$sgd_p_td = "Tư vấn | Kiểm tra hồ sơ hiện tại, tư vấn phương án thay đổi phù hợp\nSoạn hồ sơ | Soạn quyết định, biên bản họp, thông báo thay đổi theo đúng mẫu\nNộp & theo dõi | Nộp online tới cơ quan đăng ký kinh doanh, xử lý yêu cầu bổ sung (nếu có)\nBàn giao | Giao giấy chứng nhận / xác nhận thay đổi, hướng dẫn cập nhật thông tin với ngân hàng, hóa đơn, con dấu";
$sgd_p_kt = "Khảo sát | Tìm hiểu ngành nghề, quy mô hoá đơn, chứng từ của doanh nghiệp\nKý hợp đồng | Báo giá cố định theo tháng, cam kết bảo mật số liệu\nThu nhận chứng từ | Nhận chứng từ qua Zalo / email / tận nơi hằng tháng\nKê khai & báo cáo | Lập tờ khai, sổ sách, báo cáo đúng hạn, thông báo số thuế cần nộp\nBáo cáo định kỳ | Gửi báo cáo tình hình thuế, doanh thu – chi phí cho chủ doanh nghiệp";

return array(
	'groups'   => array(
		'thanh-lap-doanh-nghiep'   => array( 'Thành lập doanh nghiệp', 'building', 1, 'Dịch vụ thành lập công ty TNHH, công ty cổ phần, hộ kinh doanh, chi nhánh, văn phòng đại diện trọn gói: tư vấn loại hình, vốn điều lệ, ngành nghề; soạn và nộp hồ sơ online, giao giấy phép và con dấu tận nơi.' ),
		'thay-doi-giay-phep'       => array( 'Thay đổi giấy phép kinh doanh', 'edit', 2, 'Thay đổi nội dung đăng ký doanh nghiệp: địa chỉ trụ sở, tên công ty, người đại diện theo pháp luật, vốn điều lệ, thành viên/cổ đông, ngành nghề kinh doanh; tạm ngừng và giải thể doanh nghiệp.' ),
		'dich-vu-thue'             => array( 'Dịch vụ thuế', 'tax', 3, 'Khai thuế ban đầu cho doanh nghiệp mới, báo cáo thuế tháng/quý, quyết toán thuế cuối năm, xử lý hồ sơ hoàn thuế và hỗ trợ khi cơ quan thuế kiểm tra.' ),
		'ke-toan'                  => array( 'Dịch vụ kế toán', 'calculator', 4, 'Kế toán trọn gói theo tháng cho doanh nghiệp vừa và nhỏ, rà soát – làm lại sổ sách tồn đọng, lập báo cáo tài chính. Chi phí thấp hơn thuê kế toán nội bộ, số liệu minh bạch.' ),
	),
	'services' => array(
		// ---------------- Thành lập doanh nghiệp ----------------
		array(
			'slug'      => 'thanh-lap-cong-ty-tnhh',
			'group'     => 'thanh-lap-doanh-nghiep',
			'title'     => 'Thành lập công ty TNHH',
			'excerpt'   => 'Dịch vụ thành lập công ty TNHH một thành viên và hai thành viên trở lên trọn gói: soạn hồ sơ, nộp online, nhận giấy phép và con dấu trong 3–5 ngày làm việc.',
			'subtitle'  => 'Trọn gói từ A–Z, khách hàng không cần đi lại – có giấy phép sau 3–5 ngày làm việc',
			'price'     => 'Từ 1.000.000đ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'building',
			'featured'  => true,
			'includes'  => "Tư vấn loại hình, tên công ty, vốn điều lệ, ngành nghề phù hợp\nKiểm tra trùng tên trên hệ thống đăng ký doanh nghiệp\nSoạn điều lệ và toàn bộ hồ sơ đăng ký\nNộp hồ sơ online, theo dõi và xử lý bổ sung\nKhắc con dấu, thông báo mẫu dấu (nếu có)\nGiao giấy chứng nhận đăng ký doanh nghiệp tận nơi",
			'documents' => "Bản sao CCCD/hộ chiếu còn hiệu lực của chủ sở hữu/các thành viên góp vốn\nTên công ty dự kiến (2–3 phương án)\nĐịa chỉ trụ sở chính (có địa chỉ rõ ràng, không đặt tại căn hộ chung cư dùng để ở)\nVốn điều lệ và tỷ lệ góp vốn của từng thành viên\nNgành nghề dự kiến kinh doanh",
			'process'   => $sgd_p_tl,
			'packages'  => "Cơ bản | 1.000.000đ | Giấy chứng nhận đăng ký doanh nghiệp; Soạn điều lệ, hồ sơ; Nộp hồ sơ online; Giao kết quả tận nơi |\nTiêu chuẩn | 2.500.000đ | Toàn bộ gói Cơ bản; Con dấu tròn doanh nghiệp; Chữ ký số (token) 1 năm; Bảng hiệu công ty (mica); Tư vấn thuế ban đầu | *\nTrọn gói | 5.500.000đ | Toàn bộ gói Tiêu chuẩn; Hóa đơn điện tử 300 số; Khai thuế ban đầu; Mở tài khoản ngân hàng; Miễn phí kế toán tháng đầu |",
			'faq'       => "Thành lập công ty TNHH cần vốn tối thiểu bao nhiêu? | Với đa số ngành nghề, pháp luật không quy định vốn tối thiểu. Tuy nhiên vốn điều lệ nên phù hợp quy mô hoạt động; một số ngành nghề kinh doanh có điều kiện có yêu cầu vốn pháp định riêng.\nCông ty TNHH một thành viên và hai thành viên khác nhau thế nào? | Công ty TNHH một thành viên do một cá nhân hoặc tổ chức làm chủ sở hữu; công ty TNHH hai thành viên trở lên có từ 2 đến 50 thành viên góp vốn. Cả hai đều chịu trách nhiệm trong phạm vi vốn điều lệ.\nBao lâu phải góp đủ vốn điều lệ? | Thành viên phải góp đủ phần vốn đã cam kết trong thời hạn 90 ngày kể từ ngày được cấp giấy chứng nhận đăng ký doanh nghiệp (không kể thời gian vận chuyển, nhập khẩu tài sản góp vốn, làm thủ tục chuyển quyền sở hữu tài sản).\nTôi có phải đến cơ quan nhà nước không? | Không. Hồ sơ được nộp online, chúng tôi giao giấy chứng nhận và con dấu tận nơi.\nSau khi có giấy phép cần làm gì tiếp? | Treo bảng hiệu, mở tài khoản ngân hàng, đăng ký chữ ký số và hóa đơn điện tử, kê khai thuế ban đầu, góp vốn đúng hạn. Gói Trọn gói đã bao gồm các việc này.",
			'content'   => array(
				'Công ty TNHH phù hợp với ai?' => 'Công ty trách nhiệm hữu hạn là loại hình được lựa chọn nhiều nhất khi khởi nghiệp vì chủ sở hữu chỉ chịu trách nhiệm trong phạm vi vốn đã góp, cơ cấu quản lý gọn và dễ kiểm soát. Loại hình này phù hợp với doanh nghiệp gia đình, nhóm bạn cùng góp vốn hoặc cá nhân muốn kinh doanh chuyên nghiệp, xuất hóa đơn cho khách hàng là doanh nghiệp.',
				'Ưu điểm khi dùng dịch vụ'      => 'Hồ sơ đăng ký doanh nghiệp tuy không phức tạp nhưng dễ bị yêu cầu sửa đổi do sai mã ngành, sai cách ghi địa chỉ hoặc tên trùng/gây nhầm lẫn. Chuyên viên của chúng tôi kiểm tra trước toàn bộ thông tin, nộp đúng ngay lần đầu, giúp bạn tiết kiệm thời gian và tránh các rủi ro về thuế, hóa đơn ngay từ khi mới thành lập.',
				'Lưu ý khi chọn tên và ngành nghề' => 'Tên công ty không được trùng hoặc gây nhầm lẫn với doanh nghiệp đã đăng ký, không vi phạm thuần phong mỹ tục. Ngành nghề được ghi theo Hệ thống ngành kinh tế Việt Nam; với ngành nghề kinh doanh có điều kiện, doanh nghiệp cần đáp ứng điều kiện (giấy phép con, chứng chỉ, vốn…) trước khi hoạt động. Chúng tôi tư vấn cụ thể cho từng trường hợp.',
			),
		),
		array(
			'slug'      => 'thanh-lap-cong-ty-co-phan',
			'group'     => 'thanh-lap-doanh-nghiep',
			'title'     => 'Thành lập công ty cổ phần',
			'excerpt'   => 'Dịch vụ thành lập công ty cổ phần trọn gói: tư vấn cơ cấu cổ đông, vốn, điều lệ; soạn và nộp hồ sơ online, nhận giấy phép và con dấu nhanh chóng.',
			'subtitle'  => 'Phù hợp doanh nghiệp có từ 3 cổ đông, cần huy động vốn và mở rộng quy mô',
			'price'     => 'Từ 1.500.000đ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'users',
			'featured'  => true,
			'includes'  => "Tư vấn cơ cấu cổ đông sáng lập, tỷ lệ cổ phần, mô hình quản trị\nSoạn điều lệ, danh sách cổ đông sáng lập và hồ sơ đăng ký\nNộp hồ sơ online, xử lý bổ sung\nKhắc con dấu, giao kết quả tận nơi\nHướng dẫn góp vốn, lập sổ đăng ký cổ đông",
			'documents' => "Bản sao CCCD/hộ chiếu của tối thiểu 3 cổ đông sáng lập\nTên công ty, địa chỉ trụ sở dự kiến\nVốn điều lệ, số cổ phần mỗi cổ đông đăng ký mua\nNgười đại diện theo pháp luật, chức danh (Giám đốc/Tổng giám đốc/Chủ tịch HĐQT)\nNgành nghề dự kiến kinh doanh",
			'process'   => $sgd_p_tl,
			'packages'  => "Cơ bản | 1.500.000đ | Giấy chứng nhận đăng ký doanh nghiệp; Điều lệ, danh sách cổ đông; Nộp hồ sơ online; Giao kết quả tận nơi |\nTiêu chuẩn | 3.000.000đ | Toàn bộ gói Cơ bản; Con dấu doanh nghiệp; Chữ ký số 1 năm; Sổ đăng ký cổ đông; Tư vấn thuế ban đầu | *\nTrọn gói | 6.000.000đ | Toàn bộ gói Tiêu chuẩn; Hóa đơn điện tử 300 số; Khai thuế ban đầu; Mở tài khoản ngân hàng; Miễn phí kế toán tháng đầu |",
			'faq'       => "Công ty cổ phần cần tối thiểu bao nhiêu cổ đông? | Tối thiểu 3 cổ đông và không giới hạn số lượng tối đa.\nCông ty cổ phần có được phát hành cổ phần huy động vốn không? | Có. Đây là ưu điểm lớn của công ty cổ phần so với công ty TNHH: có thể chào bán cổ phần để huy động vốn, chuyển nhượng cổ phần linh hoạt hơn (trừ một số hạn chế với cổ đông sáng lập trong 3 năm đầu).\nNên chọn công ty TNHH hay cổ phần? | Nếu có ít thành viên và muốn quản lý gọn, nên chọn TNHH. Nếu có nhiều người cùng góp vốn, có kế hoạch gọi vốn hoặc niêm yết, nên chọn cổ phần. Chuyên viên sẽ tư vấn miễn phí theo kế hoạch của bạn.",
			'content'   => array(
				'Khi nào nên thành lập công ty cổ phần?' => 'Công ty cổ phần phù hợp với doanh nghiệp có nhiều người góp vốn, cần cơ chế chuyển nhượng cổ phần linh hoạt và có kế hoạch huy động thêm vốn từ nhà đầu tư. Cơ cấu quản trị gồm Đại hội đồng cổ đông, Hội đồng quản trị và Giám đốc/Tổng giám đốc, giúp phân quyền rõ ràng khi doanh nghiệp lớn mạnh.',
				'Những điểm cần thống nhất trước khi thành lập' => 'Các cổ đông nên thống nhất trước tỷ lệ sở hữu, người đại diện theo pháp luật, cơ chế biểu quyết, phân chia lợi nhuận và điều kiện chuyển nhượng cổ phần. Những nội dung này được ghi vào điều lệ công ty, là cơ sở giải quyết tranh chấp nội bộ về sau.',
			),
		),
		array(
			'slug'      => 'dang-ky-ho-kinh-doanh',
			'group'     => 'thanh-lap-doanh-nghiep',
			'title'     => 'Đăng ký hộ kinh doanh',
			'excerpt'   => 'Dịch vụ đăng ký hộ kinh doanh cá thể nhanh gọn cho cửa hàng, quán ăn, cơ sở sản xuất nhỏ: tư vấn ngành nghề, thuế, soạn và nộp hồ sơ thay khách hàng.',
			'subtitle'  => 'Cho cửa hàng, quán ăn, cơ sở kinh doanh nhỏ – thủ tục gọn, chi phí thấp',
			'price'     => 'Từ 800.000đ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'stamp',
			'featured'  => false,
			'includes'  => "Tư vấn ngành nghề, địa điểm kinh doanh và nghĩa vụ thuế của hộ kinh doanh\nSoạn hồ sơ đăng ký hộ kinh doanh\nNộp hồ sơ và nhận giấy chứng nhận thay khách hàng\nHướng dẫn kê khai thuế, hóa đơn cho hộ kinh doanh",
			'documents' => "Bản sao CCCD của chủ hộ (và các thành viên hộ gia đình nếu cùng đăng ký)\nĐịa chỉ địa điểm kinh doanh\nNgành nghề, vốn kinh doanh dự kiến\nGiấy tờ chứng minh quyền sử dụng địa điểm (hợp đồng thuê, giấy chứng nhận… nếu được yêu cầu)",
			'process'   => "Tư vấn | Xác định hộ kinh doanh hay công ty phù hợp hơn với kế hoạch của bạn\nSoạn hồ sơ | Soạn giấy đề nghị đăng ký hộ kinh doanh, gửi khách ký\nNộp hồ sơ | Nộp tới cơ quan đăng ký kinh doanh có thẩm quyền, theo dõi kết quả\nBàn giao | Giao giấy chứng nhận đăng ký hộ kinh doanh, hướng dẫn nghĩa vụ thuế",
			'packages'  => '',
			'faq'       => "Hộ kinh doanh và công ty khác nhau thế nào? | Hộ kinh doanh do một cá nhân hoặc các thành viên hộ gia đình làm chủ, chịu trách nhiệm bằng toàn bộ tài sản; thủ tục và sổ sách đơn giản hơn công ty. Công ty có tư cách pháp nhân, chịu trách nhiệm hữu hạn (TNHH, cổ phần), phù hợp khi cần xuất hóa đơn cho doanh nghiệp, mở rộng quy mô.\nHộ kinh doanh có được chuyển đổi thành công ty không? | Có. Pháp luật cho phép hộ kinh doanh chuyển đổi thành doanh nghiệp; chúng tôi hỗ trợ trọn gói thủ tục chuyển đổi.",
			'content'   => array(
				'Ai nên đăng ký hộ kinh doanh?' => 'Hộ kinh doanh phù hợp với các cơ sở bán lẻ, dịch vụ ăn uống, sửa chữa, sản xuất nhỏ… có quy mô vừa phải và chủ yếu bán hàng cho người tiêu dùng. Ưu điểm là thủ tục đơn giản, chế độ kế toán và thuế gọn nhẹ. Nếu bạn cần xuất hóa đơn cho doanh nghiệp, thuê nhiều lao động hoặc gọi vốn, nên cân nhắc thành lập công ty.',
			),
		),
		array(
			'slug'      => 'thanh-lap-chi-nhanh-van-phong-dai-dien',
			'group'     => 'thanh-lap-doanh-nghiep',
			'title'     => 'Thành lập chi nhánh, văn phòng đại diện, địa điểm kinh doanh',
			'excerpt'   => 'Dịch vụ đăng ký hoạt động chi nhánh, văn phòng đại diện, địa điểm kinh doanh cho doanh nghiệp đang hoạt động: tư vấn hình thức phù hợp, soạn và nộp hồ sơ trọn gói.',
			'subtitle'  => 'Mở rộng hoạt động sang địa điểm mới – đúng hình thức, đúng nghĩa vụ thuế',
			'price'     => 'Từ 1.500.000đ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'building',
			'featured'  => false,
			'includes'  => "Tư vấn chọn chi nhánh, văn phòng đại diện hay địa điểm kinh doanh\nSoạn quyết định, biên bản và hồ sơ đăng ký\nNộp hồ sơ online, nhận kết quả\nHướng dẫn đăng ký thuế, hóa đơn cho đơn vị phụ thuộc",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp (bản chụp)\nĐịa chỉ chi nhánh / văn phòng đại diện / địa điểm kinh doanh\nCCCD của người đứng đầu đơn vị\nNgành nghề hoạt động của chi nhánh (nếu có)",
			'process'   => $sgd_p_td,
			'packages'  => '',
			'faq'       => "Chi nhánh và văn phòng đại diện khác nhau thế nào? | Chi nhánh được thực hiện chức năng kinh doanh của doanh nghiệp; văn phòng đại diện chỉ làm nhiệm vụ đại diện, giao dịch, bảo vệ lợi ích của doanh nghiệp, không được kinh doanh.\nĐịa điểm kinh doanh dùng khi nào? | Khi doanh nghiệp cần một nơi bán hàng, kho, cửa hàng… mà không cần lập đơn vị có bộ máy riêng như chi nhánh.",
			'content'   => array(
				'Chọn hình thức phù hợp' => 'Tuỳ nhu cầu hoạt động tại địa điểm mới, doanh nghiệp có thể đăng ký chi nhánh, văn phòng đại diện hoặc địa điểm kinh doanh. Mỗi hình thức có phạm vi hoạt động và nghĩa vụ kê khai thuế khác nhau. Chúng tôi tư vấn hình thức tối ưu cả về pháp lý lẫn chi phí vận hành.',
			),
		),
		array(
			'slug'      => 'thanh-lap-cong-ty-von-nuoc-ngoai',
			'group'     => 'thanh-lap-doanh-nghiep',
			'title'     => 'Thành lập công ty có vốn đầu tư nước ngoài',
			'excerpt'   => 'Tư vấn và thực hiện thủ tục đầu tư cho nhà đầu tư nước ngoài: giấy chứng nhận đăng ký đầu tư, đăng ký doanh nghiệp, tài khoản vốn đầu tư trực tiếp và các giấy phép con.',
			'subtitle'  => 'Giấy chứng nhận đăng ký đầu tư + đăng ký doanh nghiệp + tài khoản vốn – một đầu mối',
			'price'     => 'Liên hệ báo giá',
			'duration'  => 'Theo hồ sơ (tư vấn cụ thể)',
			'icon'      => 'globe',
			'featured'  => false,
			'includes'  => "Tư vấn điều kiện tiếp cận thị trường cho ngành nghề dự kiến\nSoạn hồ sơ đăng ký đầu tư, đề xuất dự án\nĐăng ký doanh nghiệp, con dấu\nHỗ trợ mở tài khoản vốn đầu tư trực tiếp\nTư vấn giấy phép con, nghĩa vụ báo cáo đầu tư",
			'documents' => "Hộ chiếu (nhà đầu tư cá nhân) hoặc giấy tờ pháp lý của tổ chức (đã hợp pháp hóa lãnh sự, dịch công chứng)\nXác nhận số dư tài khoản / báo cáo tài chính chứng minh năng lực tài chính\nHợp đồng thuê địa điểm thực hiện dự án\nThông tin dự án: mục tiêu, quy mô, vốn đầu tư, tiến độ",
			'process'   => "Tư vấn sơ bộ | Đánh giá ngành nghề, điều kiện đầu tư, lộ trình và chi phí\nHồ sơ đầu tư | Soạn và nộp hồ sơ đề nghị cấp giấy chứng nhận đăng ký đầu tư\nĐăng ký doanh nghiệp | Thành lập doanh nghiệp, khắc dấu\nSau cấp phép | Mở tài khoản vốn, góp vốn, đăng ký thuế, giấy phép con (nếu có)",
			'packages'  => '',
			'faq'       => "Nhà đầu tư nước ngoài có được sở hữu 100% vốn không? | Tuỳ ngành nghề. Nhiều ngành cho phép 100% vốn nước ngoài, một số ngành bị hạn chế tỷ lệ sở hữu hoặc có điều kiện riêng theo cam kết quốc tế của Việt Nam. Chúng tôi kiểm tra cụ thể cho ngành nghề của bạn.",
			'content'   => array(
				'Quy trình tổng quan' => 'Thông thường nhà đầu tư nước ngoài cần thực hiện thủ tục cấp giấy chứng nhận đăng ký đầu tư trước, sau đó đăng ký thành lập doanh nghiệp. Thời gian phụ thuộc ngành nghề và chất lượng hồ sơ. Chúng tôi làm đầu mối duy nhất, cập nhật tiến độ thường xuyên bằng tiếng Việt hoặc tiếng Anh.',
			),
		),

		// ---------------- Thay đổi giấy phép kinh doanh ----------------
		array(
			'slug'      => 'thay-doi-dia-chi-cong-ty',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Thay đổi địa chỉ trụ sở công ty',
			'excerpt'   => 'Dịch vụ thay đổi địa chỉ trụ sở chính cùng quận/huyện hoặc khác tỉnh: soạn hồ sơ, làm thủ tục với cơ quan thuế và đăng ký kinh doanh, cập nhật hóa đơn, con dấu.',
			'subtitle'  => 'Chuyển trụ sở cùng hoặc khác tỉnh/thành – xử lý luôn thủ tục thuế',
			'price'     => 'Từ 1.000.000đ',
			'duration'  => '3 – 7 ngày làm việc',
			'icon'      => 'edit',
			'featured'  => true,
			'includes'  => "Kiểm tra tình trạng thuế trước khi chuyển (nếu khác cơ quan thuế quản lý)\nSoạn quyết định, biên bản họp, thông báo thay đổi\nNộp hồ sơ và nhận giấy chứng nhận mới\nHướng dẫn cập nhật địa chỉ trên hóa đơn điện tử, ngân hàng, bảng hiệu",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp hiện tại (bản chụp)\nĐịa chỉ trụ sở mới\nCCCD người đại diện theo pháp luật\nChữ ký số doanh nghiệp (để làm thủ tục thuế nếu chuyển khác cơ quan thuế quản lý)",
			'process'   => $sgd_p_td,
			'packages'  => "Cùng cơ quan thuế | 1.000.000đ | Soạn hồ sơ thay đổi; Nộp online; Giấy chứng nhận mới; Giao kết quả tận nơi |\nKhác cơ quan thuế | 2.500.000đ | Toàn bộ gói bên trái; Thủ tục chuyển địa điểm với cơ quan thuế; Đối chiếu, khóa sổ thuế nơi đi; Cập nhật hóa đơn điện tử | *",
			'faq'       => "Đổi địa chỉ có phải đổi con dấu không? | Mẫu dấu hiện nay không bắt buộc thể hiện địa chỉ. Nếu con dấu cũ có địa chỉ, doanh nghiệp nên khắc lại để đồng bộ.\nThời hạn đăng ký thay đổi là bao lâu? | Doanh nghiệp phải đăng ký thay đổi nội dung đăng ký doanh nghiệp trong thời hạn 10 ngày kể từ ngày có thay đổi.\nChuyển trụ sở sang tỉnh khác cần lưu ý gì? | Doanh nghiệp phải hoàn thành thủ tục với cơ quan thuế nơi đi (nộp đủ tờ khai, số thuế còn nợ) trước khi đăng ký thay đổi. Gói Khác cơ quan thuế đã bao gồm việc này.",
			'content'   => array(
				'Những việc cần làm sau khi đổi địa chỉ' => 'Sau khi có giấy chứng nhận mới, doanh nghiệp cần cập nhật địa chỉ với ngân hàng, nhà cung cấp hóa đơn điện tử, chữ ký số, hợp đồng với đối tác và treo bảng hiệu tại trụ sở mới. Chúng tôi gửi kèm danh sách kiểm tra để bạn không bỏ sót.',
			),
		),
		array(
			'slug'      => 'thay-doi-nguoi-dai-dien-ten-cong-ty',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Thay đổi tên công ty, người đại diện theo pháp luật',
			'excerpt'   => 'Dịch vụ đổi tên công ty, thay đổi người đại diện theo pháp luật, chức danh giám đốc: soạn hồ sơ đúng mẫu, nộp online, giao giấy chứng nhận mới tận nơi.',
			'subtitle'  => 'Hồ sơ chuẩn, nộp online – giấy chứng nhận mới sau 3 ngày làm việc',
			'price'     => 'Từ 1.000.000đ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'edit',
			'featured'  => false,
			'includes'  => "Kiểm tra tên mới có trùng/gây nhầm lẫn không\nSoạn quyết định, biên bản họp, thông báo thay đổi, điều lệ sửa đổi (nếu cần)\nNộp hồ sơ online và nhận kết quả\nHướng dẫn khắc lại dấu, cập nhật hóa đơn và ngân hàng",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp hiện tại (bản chụp)\nTên mới dự kiến (khi đổi tên)\nCCCD của người đại diện mới (khi đổi người đại diện)",
			'process'   => $sgd_p_td,
			'packages'  => '',
			'faq'       => "Đổi tên công ty có phải đổi mã số thuế không? | Không. Mã số doanh nghiệp (mã số thuế) giữ nguyên, chỉ thay đổi tên trên giấy chứng nhận.\nĐổi tên rồi hóa đơn cũ xử lý thế nào? | Doanh nghiệp cần cập nhật thông tin với nhà cung cấp hóa đơn điện tử để hóa đơn xuất ra mang tên mới; chúng tôi hướng dẫn chi tiết sau khi có kết quả.",
			'content'   => array(
				'Khi nào cần thay đổi?' => 'Doanh nghiệp đổi tên khi tái định vị thương hiệu, sáp nhập hoặc tránh trùng nhãn hiệu; thay đổi người đại diện theo pháp luật khi thay giám đốc hoặc chuyển nhượng vốn. Mọi thay đổi phải được đăng ký trong 10 ngày kể từ ngày có quyết định thay đổi để tránh bị xử phạt.',
			),
		),
		array(
			'slug'      => 'tang-giam-von-dieu-le',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Tăng, giảm vốn điều lệ – thay đổi thành viên, cổ đông',
			'excerpt'   => 'Dịch vụ tăng/giảm vốn điều lệ, chuyển nhượng phần vốn góp, thay đổi thành viên/cổ đông, chuyển đổi loại hình công ty; tư vấn nghĩa vụ thuế thu nhập từ chuyển nhượng vốn.',
			'subtitle'  => 'Tư vấn luôn nghĩa vụ thuế chuyển nhượng vốn – tránh rủi ro về sau',
			'price'     => 'Từ 1.500.000đ',
			'duration'  => '3 – 7 ngày làm việc',
			'icon'      => 'chart',
			'featured'  => false,
			'includes'  => "Tư vấn phương án tăng/giảm vốn, chuyển nhượng phù hợp\nSoạn hợp đồng chuyển nhượng, biên bản thanh lý, quyết định, biên bản họp\nKê khai thuế TNCN/TNDN từ chuyển nhượng vốn (nếu có)\nNộp hồ sơ thay đổi và nhận kết quả",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp hiện tại\nCCCD của thành viên/cổ đông mới (nếu có)\nThông tin vốn sau thay đổi, giá chuyển nhượng\nBáo cáo tài chính gần nhất (với trường hợp giảm vốn)",
			'process'   => $sgd_p_td,
			'packages'  => '',
			'faq'       => "Chuyển nhượng vốn có phải nộp thuế không? | Có thể phát sinh thuế thu nhập cá nhân (với cá nhân) hoặc thuế thu nhập doanh nghiệp (với tổ chức) nếu có thu nhập từ chuyển nhượng. Chúng tôi tư vấn và kê khai thay bạn.\nTăng vốn điều lệ có làm tăng thuế không? | Tăng vốn không trực tiếp làm phát sinh thuế, nhưng cần góp đủ vốn đúng hạn và ghi nhận đúng trên sổ sách kế toán.",
			'content'   => array(
				'Lưu ý khi thay đổi vốn' => 'Thay đổi vốn và thành viên ảnh hưởng tới quyền biểu quyết, phân chia lợi nhuận và nghĩa vụ thuế. Hồ sơ cần thể hiện đầy đủ việc góp vốn, thanh toán chuyển nhượng để làm căn cứ khi cơ quan thuế kiểm tra. Chúng tôi soạn bộ hồ sơ đầy đủ, nhất quán giữa giấy tờ pháp lý và sổ sách kế toán.',
			),
		),
		array(
			'slug'      => 'bo-sung-nganh-nghe-kinh-doanh',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Bổ sung, thay đổi ngành nghề kinh doanh',
			'excerpt'   => 'Dịch vụ bổ sung, rút bớt ngành nghề kinh doanh: tra mã ngành chính xác theo Hệ thống ngành kinh tế Việt Nam, tư vấn điều kiện kinh doanh, nộp hồ sơ trọn gói.',
			'subtitle'  => 'Tra mã ngành chính xác, tư vấn điều kiện kinh doanh trước khi đăng ký',
			'price'     => 'Từ 800.000đ',
			'duration'  => '3 ngày làm việc',
			'icon'      => 'doc',
			'featured'  => false,
			'includes'  => "Tra cứu, chọn mã ngành phù hợp với hoạt động thực tế\nTư vấn điều kiện với ngành nghề kinh doanh có điều kiện\nSoạn và nộp thông báo thay đổi ngành nghề\nGửi xác nhận thay đổi nội dung đăng ký doanh nghiệp",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp hiện tại (bản chụp)\nMô tả hoạt động kinh doanh muốn bổ sung",
			'process'   => $sgd_p_td,
			'packages'  => '',
			'faq'       => "Bổ sung ngành nghề có được cấp giấy chứng nhận mới không? | Thay đổi ngành nghề được cơ quan đăng ký kinh doanh cập nhật và cấp giấy xác nhận thay đổi nội dung đăng ký doanh nghiệp; giấy chứng nhận đăng ký doanh nghiệp không ghi ngành nghề.\nKinh doanh ngành chưa đăng ký có bị phạt không? | Có. Doanh nghiệp kinh doanh ngành nghề chưa đăng ký có thể bị xử phạt vi phạm hành chính, vì vậy nên bổ sung trước khi phát sinh hoạt động và xuất hóa đơn.",
			'content'   => array(
				'Vì sao cần chọn đúng mã ngành?' => 'Mã ngành không chỉ là thủ tục: nó liên quan đến điều kiện kinh doanh, ưu đãi thuế và cả việc đấu thầu, ký hợp đồng với đối tác. Chọn sai hoặc thiếu mã ngành có thể khiến doanh nghiệp bị từ chối hồ sơ thầu hoặc bị xử phạt. Chúng tôi tra cứu và đề xuất danh sách mã ngành đầy đủ, đúng hoạt động thực tế.',
			),
		),
		array(
			'slug'      => 'tam-ngung-giai-the-doanh-nghiep',
			'group'     => 'thay-doi-giay-phep',
			'title'     => 'Tạm ngừng kinh doanh, giải thể doanh nghiệp',
			'excerpt'   => 'Dịch vụ tạm ngừng kinh doanh, tiếp tục kinh doanh trước hạn, giải thể công ty: quyết toán thuế, đóng mã số thuế, hoàn tất thủ tục với cơ quan đăng ký kinh doanh.',
			'subtitle'  => 'Đóng doanh nghiệp đúng luật, không để lại nợ thuế và rủi ro cho chủ sở hữu',
			'price'     => 'Từ 1.000.000đ',
			'duration'  => 'Tạm ngừng: 3 ngày · Giải thể: theo hồ sơ',
			'icon'      => 'shield',
			'featured'  => false,
			'includes'  => "Tư vấn chọn tạm ngừng hay giải thể\nRà soát nghĩa vụ thuế, hóa đơn, bảo hiểm còn tồn\nQuyết toán thuế, đóng mã số thuế (khi giải thể)\nSoạn và nộp hồ sơ tạm ngừng / giải thể",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nThời gian dự kiến tạm ngừng (với tạm ngừng)\nSổ sách, chứng từ kế toán, báo cáo tài chính (với giải thể)\nChữ ký số doanh nghiệp",
			'process'   => "Tư vấn | Đánh giá tình trạng thuế, công nợ, lao động\nXử lý nghĩa vụ | Nộp đủ tờ khai, quyết toán thuế, hủy hóa đơn còn lại (khi giải thể)\nNộp hồ sơ | Thông báo tạm ngừng hoặc hồ sơ giải thể tới cơ quan đăng ký kinh doanh\nHoàn tất | Nhận xác nhận tạm ngừng / thông báo doanh nghiệp đã giải thể",
			'packages'  => "Tạm ngừng kinh doanh | 1.000.000đ | Soạn thông báo tạm ngừng; Nộp hồ sơ online; Nhận giấy xác nhận; Tư vấn nghĩa vụ thuế khi tạm ngừng |\nGiải thể doanh nghiệp | Từ 5.000.000đ | Rà soát sổ sách, nghĩa vụ thuế; Quyết toán thuế, đóng mã số thuế; Hồ sơ giải thể; Theo dõi đến khi hoàn tất | *",
			'faq'       => "Tạm ngừng kinh doanh cần báo trước bao lâu? | Doanh nghiệp phải thông báo bằng văn bản cho cơ quan đăng ký kinh doanh chậm nhất 3 ngày làm việc trước ngày tạm ngừng hoặc tiếp tục kinh doanh trước thời hạn.\nTạm ngừng có phải nộp báo cáo thuế không? | Trong thời gian tạm ngừng trọn năm hoặc trọn quý, doanh nghiệp thường không phải nộp hồ sơ khai thuế của kỳ đó (trừ một số trường hợp). Nếu tạm ngừng không trọn năm, vẫn phải nộp báo cáo tài chính và quyết toán năm.\nGiải thể mất bao lâu? | Phụ thuộc tình trạng sổ sách và việc quyết toán thuế; doanh nghiệp có sổ sách đầy đủ sẽ nhanh hơn nhiều. Chúng tôi báo thời gian cụ thể sau khi rà soát.",
			'content'   => array(
				'Tạm ngừng hay giải thể?' => 'Nếu chỉ muốn dừng hoạt động một thời gian để tái cấu trúc, tạm ngừng là lựa chọn tiết kiệm. Nếu không còn kế hoạch kinh doanh, nên giải thể dứt điểm để tránh phát sinh nghĩa vụ báo cáo và rủi ro bị đưa vào danh sách doanh nghiệp không hoạt động tại địa chỉ đăng ký – ảnh hưởng tới người đại diện khi thành lập doanh nghiệp mới.',
			),
		),

		// ---------------- Dịch vụ thuế ----------------
		array(
			'slug'      => 'khai-thue-ban-dau',
			'group'     => 'dich-vu-thue',
			'title'     => 'Khai thuế ban đầu cho doanh nghiệp mới',
			'excerpt'   => 'Dịch vụ khai thuế ban đầu cho doanh nghiệp mới thành lập: đăng ký phương pháp tính thuế, chữ ký số, hóa đơn điện tử, nộp thuế điện tử, đăng ký tài khoản ngân hàng với cơ quan thuế.',
			'subtitle'  => 'Làm đúng ngay từ đầu – tránh bị phạt chậm nộp ngay tháng đầu tiên',
			'price'     => 'Từ 1.000.000đ',
			'duration'  => '3 – 5 ngày làm việc',
			'icon'      => 'tax',
			'featured'  => true,
			'includes'  => "Tư vấn phương pháp tính thuế GTGT, kỳ kê khai phù hợp\nĐăng ký chữ ký số, tài khoản giao dịch thuế điện tử\nĐăng ký sử dụng hóa đơn điện tử\nKê khai và hướng dẫn nộp các khoản thuế, phí ban đầu\nTư vấn chế độ kế toán, lưu trữ chứng từ",
			'documents' => "Giấy chứng nhận đăng ký doanh nghiệp\nCCCD người đại diện theo pháp luật\nThông tin tài khoản ngân hàng của doanh nghiệp\nChữ ký số (nếu đã có)",
			'process'   => $sgd_p_kt,
			'packages'  => '',
			'faq'       => "Doanh nghiệp mới thành lập cần làm gì về thuế? | Đăng ký chữ ký số và tài khoản thuế điện tử, đăng ký hóa đơn điện tử, xác định kỳ kê khai, thông báo tài khoản ngân hàng, kê khai và nộp các khoản thuế, phí theo quy định hiện hành. Chúng tôi lập danh sách việc cần làm cho từng doanh nghiệp.\nChưa có doanh thu có phải nộp tờ khai không? | Có. Kể cả khi chưa phát sinh doanh thu, doanh nghiệp vẫn phải nộp tờ khai thuế đúng hạn (khai không phát sinh), nếu không sẽ bị phạt chậm nộp tờ khai.",
			'content'   => array(
				'Vì sao khai thuế ban đầu quan trọng?' => 'Nhiều doanh nghiệp mới bị phạt ngay trong những tháng đầu vì không biết phải nộp tờ khai dù chưa có doanh thu, hoặc đăng ký sai kỳ kê khai. Làm đúng thủ tục ban đầu giúp doanh nghiệp xuất hóa đơn hợp lệ ngay khi có hợp đồng đầu tiên và tránh các khoản phạt không đáng có.',
			),
		),
		array(
			'slug'      => 'bao-cao-thue-hang-thang-quy',
			'group'     => 'dich-vu-thue',
			'title'     => 'Báo cáo thuế hàng tháng, hàng quý',
			'excerpt'   => 'Dịch vụ báo cáo thuế định kỳ: tờ khai thuế GTGT, thuế TNCN, tạm tính TNDN, báo cáo tình hình sử dụng hóa đơn (nếu có). Nộp đúng hạn, thông báo số thuế cần nộp trước hạn.',
			'subtitle'  => 'Nộp tờ khai đúng hạn, nhắc lịch nộp thuế – chủ doanh nghiệp yên tâm kinh doanh',
			'price'     => 'Từ 500.000đ/tháng',
			'duration'  => 'Định kỳ theo tháng/quý',
			'icon'      => 'chart',
			'featured'  => false,
			'includes'  => "Kiểm tra tính hợp lệ của hóa đơn đầu vào, đầu ra\nLập và nộp tờ khai thuế GTGT, TNCN theo tháng/quý\nTạm tính thuế TNDN, tư vấn tối ưu chi phí hợp lệ\nThông báo số thuế phải nộp và hạn nộp",
			'documents' => "Hóa đơn đầu vào, đầu ra trong kỳ (hệ thống hóa đơn điện tử)\nBảng lương, hợp đồng lao động (nếu có)\nChữ ký số doanh nghiệp",
			'process'   => $sgd_p_kt,
			'packages'  => "Không phát sinh | 500.000đ/tháng | Tờ khai thuế không phát sinh; Theo dõi hạn nộp; Tư vấn qua Zalo |\nDưới 20 hóa đơn | 1.000.000đ/tháng | Kiểm tra hóa đơn; Tờ khai GTGT, TNCN; Tạm tính TNDN; Thông báo số thuế phải nộp | *\nTrên 20 hóa đơn | Liên hệ | Toàn bộ gói giữa; Báo giá theo số lượng chứng từ thực tế |",
			'faq'       => "Kê khai thuế GTGT theo tháng hay theo quý? | Doanh nghiệp mới thành lập và doanh nghiệp có doanh thu năm trước từ 50 tỷ đồng trở xuống thường được khai theo quý; trên 50 tỷ đồng khai theo tháng. Chúng tôi xác định kỳ khai đúng cho doanh nghiệp của bạn.\nHạn nộp tờ khai thuế là khi nào? | Khai theo tháng: chậm nhất ngày 20 của tháng sau. Khai theo quý: chậm nhất ngày cuối cùng của tháng đầu quý sau.",
			'content'   => array(
				'Lịch nộp tờ khai cần nhớ' => 'Tờ khai thuế GTGT và TNCN theo tháng nộp chậm nhất ngày 20 tháng sau; theo quý nộp chậm nhất ngày cuối cùng của tháng đầu quý tiếp theo. Chậm nộp tờ khai hoặc chậm nộp tiền thuế đều bị xử phạt và tính tiền chậm nộp. Dịch vụ của chúng tôi nhắc lịch và nộp thay doanh nghiệp, kèm báo cáo số thuế phải nộp trước hạn.',
			),
		),
		array(
			'slug'      => 'quyet-toan-thue-cuoi-nam',
			'group'     => 'dich-vu-thue',
			'title'     => 'Quyết toán thuế cuối năm, báo cáo tài chính',
			'excerpt'   => 'Dịch vụ lập báo cáo tài chính năm, quyết toán thuế TNDN, quyết toán thuế TNCN; rà soát chi phí hợp lệ để giảm rủi ro khi cơ quan thuế kiểm tra.',
			'subtitle'  => 'Báo cáo tài chính + quyết toán TNDN, TNCN – nộp đúng hạn, số liệu khớp đúng',
			'price'     => 'Từ 3.000.000đ',
			'duration'  => '5 – 15 ngày làm việc',
			'icon'      => 'doc',
			'featured'  => true,
			'includes'  => "Rà soát sổ sách, chứng từ, đối chiếu công nợ, kho, tài sản\nLập báo cáo tài chính năm\nLập tờ khai quyết toán thuế TNDN, TNCN\nĐiều chỉnh sai sót, loại chi phí không hợp lệ trước khi nộp\nNộp hồ sơ, gửi bản cứng/bản điện tử cho doanh nghiệp",
			'documents' => "Hóa đơn, chứng từ, sổ sách trong năm\nSao kê tài khoản ngân hàng cả năm\nBảng lương, hợp đồng lao động, chứng từ bảo hiểm\nBiên bản kiểm kê kho, tài sản cuối năm (nếu có)",
			'process'   => "Tiếp nhận chứng từ | Nhận và phân loại chứng từ của cả năm\nRà soát | Đối chiếu sổ sách – tờ khai – ngân hàng, phát hiện sai lệch\nLập báo cáo | Lập báo cáo tài chính, tờ khai quyết toán TNDN, TNCN\nDuyệt & nộp | Giải trình số liệu với chủ doanh nghiệp, nộp hồ sơ đúng hạn",
			'packages'  => "Doanh nghiệp nhỏ | 3.000.000đ | Báo cáo tài chính; Quyết toán TNDN; Quyết toán TNCN; Dưới 100 chứng từ/năm |\nDoanh nghiệp vừa | 6.000.000đ | Toàn bộ gói nhỏ; Rà soát chi phí hợp lệ; Đối chiếu công nợ, kho; 100 – 500 chứng từ/năm | *\nTheo hồ sơ | Liên hệ | Trên 500 chứng từ/năm; Doanh nghiệp sản xuất, xây dựng, xuất nhập khẩu |",
			'faq'       => "Hạn nộp quyết toán thuế năm là khi nào? | Chậm nhất là ngày cuối cùng của tháng thứ 3 kể từ ngày kết thúc năm tài chính (ví dụ năm tài chính theo năm dương lịch: ngày 31/3 năm sau).\nDoanh nghiệp không có doanh thu có phải nộp báo cáo tài chính không? | Có. Doanh nghiệp đang hoạt động vẫn phải lập và nộp báo cáo tài chính, quyết toán thuế dù không phát sinh doanh thu.",
			'content'   => array(
				'Vì sao cần rà soát trước khi quyết toán?' => 'Quyết toán là lúc toàn bộ số liệu cả năm được tổng hợp: chi phí không có hóa đơn hợp lệ, hóa đơn thanh toán bằng tiền mặt vượt ngưỡng cho phép, chênh lệch giữa tờ khai và sổ sách… đều có thể bị loại khi kiểm tra. Rà soát trước giúp điều chỉnh kịp thời, giảm số thuế bị truy thu và tiền phạt.',
			),
		),
		array(
			'slug'      => 'hoan-thue-gtgt',
			'group'     => 'dich-vu-thue',
			'title'     => 'Hoàn thuế GTGT, giải trình với cơ quan thuế',
			'excerpt'   => 'Dịch vụ lập hồ sơ hoàn thuế GTGT, giải trình, làm việc với cơ quan thuế khi kiểm tra, thanh tra; xử lý hồ sơ thuế tồn đọng, nộp chậm.',
			'subtitle'  => 'Chuẩn bị hồ sơ chặt chẽ, đồng hành cùng doanh nghiệp khi làm việc với cơ quan thuế',
			'price'     => 'Liên hệ báo giá',
			'duration'  => 'Theo hồ sơ',
			'icon'      => 'shield',
			'featured'  => false,
			'includes'  => "Đánh giá điều kiện hoàn thuế\nRà soát hóa đơn, chứng từ thanh toán, hợp đồng\nLập hồ sơ đề nghị hoàn thuế\nĐại diện làm việc, giải trình với cơ quan thuế",
			'documents' => "Tờ khai thuế các kỳ đề nghị hoàn\nHóa đơn, hợp đồng, chứng từ thanh toán qua ngân hàng\nTờ khai hải quan (với hàng xuất khẩu)",
			'process'   => $sgd_p_kt,
			'packages'  => '',
			'faq'       => "Trường hợp nào được hoàn thuế GTGT? | Một số trường hợp phổ biến: hàng hóa, dịch vụ xuất khẩu có số thuế đầu vào chưa khấu trừ hết theo điều kiện luật định; dự án đầu tư; giải thể, chấm dứt hoạt động… Mỗi trường hợp có điều kiện riêng, cần đánh giá cụ thể.",
			'content'   => array(
				'Hồ sơ hoàn thuế cần chặt chẽ' => 'Hồ sơ hoàn thuế thường được kiểm tra kỹ trước hoặc sau khi hoàn. Hóa đơn, hợp đồng, chứng từ thanh toán qua ngân hàng và tờ khai phải khớp nhau. Chúng tôi rà soát toàn bộ trước khi nộp, chuẩn bị sẵn giải trình để rút ngắn thời gian xử lý.',
			),
		),

		// ---------------- Kế toán ----------------
		array(
			'slug'      => 'ke-toan-tron-goi',
			'group'     => 'ke-toan',
			'title'     => 'Kế toán trọn gói cho doanh nghiệp',
			'excerpt'   => 'Dịch vụ kế toán thuế trọn gói theo tháng: kê khai thuế, sổ sách kế toán, báo cáo tài chính, quyết toán thuế năm. Chi phí cố định, tiết kiệm hơn thuê kế toán nội bộ.',
			'subtitle'  => 'Chỉ từ 500.000đ/tháng – thay thế một kế toán nội bộ, số liệu minh bạch',
			'price'     => 'Từ 500.000đ/tháng',
			'duration'  => 'Theo hợp đồng (tháng/năm)',
			'icon'      => 'calculator',
			'featured'  => true,
			'includes'  => "Kê khai thuế GTGT, TNCN, TNDN theo tháng/quý\nHạch toán, lập sổ sách kế toán theo chế độ hiện hành\nLập bảng lương, kê khai bảo hiểm xã hội (gói nâng cao)\nLập báo cáo tài chính, quyết toán thuế cuối năm\nTư vấn chi phí hợp lệ, tối ưu thuế đúng luật\nĐại diện làm việc với cơ quan thuế",
			'documents' => "Hóa đơn đầu vào, đầu ra hằng tháng\nSao kê ngân hàng\nHợp đồng mua bán, hợp đồng lao động, bảng chấm công\nChữ ký số doanh nghiệp",
			'process'   => $sgd_p_kt,
			'packages'  => "Khởi nghiệp | 500.000đ/tháng | Chưa phát sinh hoặc dưới 10 hóa đơn/tháng; Tờ khai thuế tháng/quý; Sổ sách kế toán; Báo cáo tài chính năm |\nTiêu chuẩn | 1.500.000đ/tháng | Dưới 40 hóa đơn/tháng; Toàn bộ gói Khởi nghiệp; Bảng lương, thuế TNCN; Báo cáo quản trị quý | *\nNâng cao | 3.000.000đ/tháng | Dưới 100 hóa đơn/tháng; Toàn bộ gói Tiêu chuẩn; Kê khai bảo hiểm xã hội; Theo dõi công nợ, kho |",
			'faq'       => "Dịch vụ kế toán trọn gói có hợp pháp không? | Có. Doanh nghiệp được thuê dịch vụ kế toán của tổ chức, cá nhân đủ điều kiện kinh doanh dịch vụ kế toán theo Luật Kế toán. Hợp đồng và trách nhiệm được quy định rõ ràng.\nChi phí có tăng khi số hóa đơn tăng không? | Phí được tính theo số lượng chứng từ trung bình mỗi tháng. Khi quy mô thay đổi, chúng tôi báo trước và điều chỉnh theo bảng giá công khai.\nSố liệu có được bảo mật không? | Có. Hợp đồng có điều khoản bảo mật; nhân sự chỉ tiếp cận dữ liệu cần thiết cho công việc.\nTôi có thể theo dõi tình hình thuế không? | Có. Hằng tháng/quý chúng tôi gửi báo cáo số thuế phải nộp, doanh thu – chi phí và các lưu ý cho chủ doanh nghiệp.",
			'content'   => array(
				'Vì sao doanh nghiệp nhỏ nên thuê kế toán dịch vụ?' => 'Với doanh nghiệp vừa và nhỏ, khối lượng chứng từ thường chưa đủ để duy trì một kế toán toàn thời gian, trong khi yêu cầu chuyên môn về thuế lại cao. Dịch vụ kế toán trọn gói giúp tiết kiệm chi phí lương, bảo hiểm, phần mềm; đồng thời được một đội ngũ có kinh nghiệm theo dõi, giảm rủi ro sai sót.',
				'Cam kết của chúng tôi' => 'Nộp tờ khai đúng hạn; nếu bị phạt do lỗi của chúng tôi, chúng tôi chịu toàn bộ tiền phạt. Báo cáo minh bạch, giải thích số liệu dễ hiểu cho chủ doanh nghiệp. Bàn giao đầy đủ sổ sách khi kết thúc hợp đồng.',
			),
		),
		array(
			'slug'      => 'ra-soat-lam-lai-so-sach-ke-toan',
			'group'     => 'ke-toan',
			'title'     => 'Rà soát, làm lại sổ sách kế toán',
			'excerpt'   => 'Dịch vụ rà soát, hoàn thiện và làm lại sổ sách kế toán tồn đọng nhiều năm; xử lý sai lệch giữa tờ khai và sổ sách trước khi quyết toán, thanh tra thuế.',
			'subtitle'  => 'Xử lý sổ sách tồn đọng, sai lệch – chuẩn bị sẵn sàng khi quyết toán, thanh tra',
			'price'     => 'Từ 2.000.000đ/năm tài chính',
			'duration'  => 'Theo khối lượng chứng từ',
			'icon'      => 'doc',
			'featured'  => false,
			'includes'  => "Kiểm tra toàn bộ chứng từ, hóa đơn, tờ khai đã nộp\nPhát hiện, lập danh sách sai sót và rủi ro\nHạch toán lại, lập sổ sách đầy đủ theo chế độ kế toán\nKhai bổ sung, điều chỉnh tờ khai (nếu cần)\nIn, đóng sổ, bàn giao bộ sổ hoàn chỉnh",
			'documents' => "Chứng từ, hóa đơn các năm cần rà soát\nTờ khai thuế, báo cáo tài chính đã nộp\nSao kê ngân hàng các năm tương ứng",
			'process'   => $sgd_p_kt,
			'packages'  => '',
			'faq'       => "Sổ sách bỏ trống nhiều năm có làm lại được không? | Được, nếu còn đủ hóa đơn, chứng từ gốc. Chúng tôi sẽ đánh giá mức độ đầy đủ và báo trước các rủi ro có thể phát sinh.\nKhi nào cần rà soát sổ sách? | Trước khi quyết toán năm, trước khi cơ quan thuế kiểm tra/thanh tra, khi thay kế toán, khi chuẩn bị giải thể hoặc chuyển nhượng doanh nghiệp.",
			'content'   => array(
				'Hậu quả của sổ sách không đầy đủ' => 'Sổ sách thiếu hoặc không khớp với tờ khai có thể khiến doanh nghiệp bị loại chi phí, ấn định thuế, truy thu và phạt khi cơ quan thuế kiểm tra. Rà soát sớm giúp doanh nghiệp chủ động khai bổ sung, giảm đáng kể tiền phạt so với khi bị phát hiện.',
			),
		),
	),
);
